### ISSUE TITLE
17.11+ System.IO.IOException: Connection forcibly closed by remote host

### ISSUE THREAD

**Issue by Sterlinghv** [microsoft/codecoverage#178]
### Issue Description

After upgrading `Microsoft.NET.Test.Sdk` from version `17.10.0` to `17.11.0`, our AzureDevOps test pipeline task encounters a `System.IO.IOException` at the very beginning of the run.

### Steps to Reproduce

Use `Microsoft.NET.Test.Sdk` version `17.11.0` or above
Run `dotnet test` via the `DotNetCoreCLI@2` in an AzureDevOps pipeline:
```
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: <project solution>
```

### Expected Behavior
Test run as expected with no IO exception at the start

###  Actual Behavior

Error seen in the AzureDevops test pipeline log:
```
System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Flush()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.WriteAndFlushToChannel(String rawMessage) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/SocketCommunicationManager.cs:line 413
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionRequestSender.SendAfterTestRunEndAndGetResult(ITestMessageEventHandler runEventsHandler, Boolean isCancelled) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/DataCollectionRequestSender.cs:line 155
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyDataCollectionManager.<>c__DisplayClass20_0.<AfterTestRunEnd>b__0() in /_/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/ProxyDataCollectionManager.cs:line 155
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyDataCollectionManager.InvokeDataCollectionServiceAction(Action action, ITestMessageEventHandler runEventsHandler) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/ProxyDataCollectionManager.cs:line 288
```

### Environment
Windows Server 2016 inside a AzureDevOps agent pipeline job

### Additional Notes
This is not happening on version `17.10.0` or presumably earlier. Seems to be happening at [ProxyDataCollectionManager.cs ](https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/ProxyDataCollectionManager.cs) line 288

I'm not sure what is trying to be written/connected when the issue happens

**Comment by v-mykhalchuk** [comment]
@fhnaseer I have collected the logs without coverlet and will share you those in some time the same way I shared previous ones.

Also I have tried the dotnet-coverage and it is failing if I provide same arguments as for original dotnet test command except for `--collect`, and stops failing if I exclude `--settings` argument. Alternatively it succeeds if I comment out several tests that are testing our model classes for certain things those has to conform to, like existence of default constructor, all properties being read-write, and stuff like that, using Reflection. 
I'm not sure if this failure is related to the main one in any way, but removing those tests seemingly had no impact for initial `dotnet test` command.

**Comment by v-mykhalchuk** [comment]
@fhnaseer actually, commenting the tests with the reflection removed part of the issue. In the shared logs there are lines like:
```
2025-07-03T10:54:18.3972536Z Data collector 'Blame' message: The specified inactivity time of 2 minutes has elapsed. Collecting hang dumps from testhost and its child processes.
...
2025-07-03T10:54:19.3726051Z The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
2025-07-03T10:54:19.3726566Z The test running when the crash occurred: 
2025-07-03T10:54:19.3726869Z CompanyName.ProductName.Web.Model.UnitTests.ModelTests.AllModels_Props_MustSucceeded
```
And those are pointing to the mentioned above tests that are scanning the models, and those errors are gone now.
Possibly the test hosts were shut down due to blame setting we have. Likely these tests are taking significant time now, after the update of test SDK.
The sample code from the test like this below, and it is run on hundreds of types at times:
```
    public static void TestModelProperties(IEnumerable<Type> types)
    {
        foreach (var type in types)
        {
            var typeInfo = type.GetTypeInfo();

            if (typeInfo.IsInterface || typeInfo.IsAbstract || typeInfo.ContainsGenericParameters)
            {
                continue;
            }

            var ctors = typeInfo.DeclaredConstructors.Where(c => c.IsPublic).ToArray();
            var ctor  = ctors.FirstOrDefault(c => c.GetParameters().Length == 0);

            if ((ctor == null && ctors.Length != 0))
            {
                continue;
            }

            var entity = Activator.CreateInstance(type);
            var props  = type.GetRuntimeProperties();

            foreach (var propertyInfo in props)
            {
                var setter = propertyInfo.GetSetMethod();
                var getter = propertyInfo.GetGetMethod();

                var value = getter?.Invoke(entity, []);
                _ = setter?.Invoke(entity, [value]);
            }
        }
    }
```

**Comment by v-mykhalchuk** [comment]
@fhnaseer when I run like this with all the tests enabled, it still fails with the same symptoms (Data collector 'Blame' message: The specified inactivity time of 2 minutes has elapsed. Collecting hang dumps from testhost and its child processes.)

`dotnet-coverage collect --settings test.runsettings "dotnet test MySolution.sln --no-build --blame --blame-hang --blame-hang-dump-type full --blame-hang-timeout 120000 --configuration release -v diag"`

**Comment by fhnaseer** [comment]
> dotnet-coverage collect --settings test.runsettings "dotnet test MySolution.sln --no-build --blame --blame-hang --blame-hang-dump-type full --blame-hang-timeout 120000 --configuration release -v diag"

And if you just run `dotnet test MySolution.sln --no-build --blame --blame-hang --blame-hang-dump-type full --blame-hang-timeout 120000 --configuration release -v diag`, then what happens?

**Comment by fhnaseer** [comment]
> [@fhnaseer](https://github.com/fhnaseer) actually, commenting the tests with the reflection removed part of the issue. In the shared logs there are lines like:
> 
> ```
> 2025-07-03T10:54:18.3972536Z Data collector 'Blame' message: The specified inactivity time of 2 minutes has elapsed. Collecting hang dumps from testhost and its child processes.
> ...
> 2025-07-03T10:54:19.3726051Z The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
> 2025-07-03T10:54:19.3726566Z The test running when the crash occurred: 
> 2025-07-03T10:54:19.3726869Z CompanyName.ProductName.Web.Model.UnitTests.ModelTests.AllModels_Props_MustSucceeded
> ```
> 
> And those are pointing to the mentioned above tests that are scanning the models, and those errors are gone now. Possibly the test hosts were shut down due to blame setting we have. Likely these tests are taking significant time now, after the update of test SDK. The sample code from the test like this below, and it is run on hundreds of types at times:
> 
> ```
>     public static void TestModelProperties(IEnumerable<Type> types)
>     {
>         foreach (var type in types)
>         {
>             var typeInfo = type.GetTypeInfo();
> 
>             if (typeInfo.IsInterface || typeInfo.IsAbstract || typeInfo.ContainsGenericParameters)
>             {
>                 continue;
>             }
> 
>             var ctors = typeInfo.DeclaredConstructors.Where(c => c.IsPublic).ToArray();
>             var ctor  = ctors.FirstOrDefault(c => c.GetParameters().Length == 0);
> 
>             if ((ctor == null && ctors.Length != 0))
>             {
>                 continue;
>             }
> 
>             var entity = Activator.CreateInstance(type);
>             var props  = type.GetRuntimeProperties();
> 
>             foreach (var propertyInfo in props)
>             {
>                 var setter = propertyInfo.GetSetMethod();
>                 var getter = propertyInfo.GetGetMethod();
> 
>                 var value = getter?.Invoke(entity, []);
>                 _ = setter?.Invoke(entity, [value]);
>             }
>         }
>     }
> ```

For this project, can you run `dotnet-coverage instrument thisassmebly.dll` and see if it works?



> [@fhnaseer](https://github.com/fhnaseer) when I run like this with all the tests enabled, it still fails with the same symptoms (Data collector 'Blame' message: The specified inactivity time of 2 minutes has elapsed. Collecting hang dumps from testhost and its child processes.)
> 
> `dotnet-coverage collect --settings test.runsettings "dotnet test MySolution.sln --no-build --blame --blame-hang --blame-hang-dump-type full --blame-hang-timeout 120000 --configuration release -v diag"`

Can you please run this command with log parameters and share these logs? https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage#command-mode

**Comment by v-mykhalchuk** [comment]
@fhnaseer sorry for late response, we had some pretty busy few weeks.

On the above request, I was not able to execute neither of those to share the details to you.

For Instrument command:
I tried to run this like: `cd CompanyName.ProductName.Web.Model.UnitTests\bin\Release\ & dotnet-coverage instrument CompanyName.ProductName.Web.Model.UnitTests.dll` and got a message `Module was not instrumented. Reason: path_is_excluded.`
Tried for Debug configuration as well and no luck.

For the log parameters, I tried to run like this: `dotnet-coverage collect --settings test.runsettings -ll Verbose -l "E:/tmp/logs_dotnetcoverage_4/" "dotnet test MySolution.sln --no-build --blame --blame-hang --blame-hang-dump-type full --blame-hang-timeout 120000 --configuration release -v diag"` and that resulted into empty folder, no logs whatsoever. 
But there's an observation - I tried to run this with and without switch `-ll Verbose` and I got many more crashed test hosts with the switch. That could mean that the issue may be performache related. Verbose logging likely requires more resources so less resources are available for the tests to run and those either crash or time out. Unfortunately, it did not print any exception details on why the host crashed.

I will continue looking into this tomorrow

**Comment by fhnaseer** [comment]
@timpaulus-fsw Thanks for sharing the repro with us. By looking at the stack trace, it seems like mono.cecil is throwing exception. I do not have pdbs in our dev environment. Can you please share system.pdb so that we can find the root issue (code coverage or mono.cecil)?

**Comment by fhnaseer** [comment]
> A quick update - we have switched to a beefier build agent as part of infrastructure refresh and the issue just went away, and currently does not reproduce at all. With that said, it's very likely that the issue was occurring due to some kind of resource contention and went away when the run got more resources available. It's hard to tell what provoked higher system resource usage with the update Microsoft.NET.Test.Sdk.

Closing this issue for now. To summarize, issue was happening because invalid pdbs were present in GAC folder for framework libs e.g. system.dll. Removing these pdbs fix the issue. Also, GAC folder can be added in exclude list to avoid this issue.

>I have attached privately the following [here] (https://developercommunity.visualstudio.com/t/MicrosoftNETTestSDK-1711-SystemIO/10840657#T-N10965749):

/MinimalReproducibleExample: The sample project which failed
/Logs: The logs of a pipeline run of the sample in our environment
Once for version 17.0.0 which is sucsessful
and once for 17.14.1 which failed

I tried to reproduce this with the latest code coverage, and issue did not reproduce. 

> The .datacollector. log file had the following exceptions when trying to read a .pdb file from the GAC of .NET Framework with version 17.14.1 of Microsoft.NET.Test.Sdk (see attachment for full logs):

Logs are fine as we are trying to find and load matching pdb for system.dll and we report failure in the logs.
